### ISSUE TITLE
Publish the extension to OpenVSX

### ISSUE THREAD

**Issue by ahaasler** [remarkjs/vscode-remark#31]
Hi, I'm a [VSCodium](https://github.com/VSCodium/vscodium) user, a FLOSS version of VS Code. It's the same code but without Microsoft's telemetry, branding and licensing.

I would like to request, if possible, to add the Remark for VSCode extension to the [open-vsx.org](https://open-vsx.org/) market as it is unclear if it's legal to use the official Microsoft extension marketplace on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).

Additional information on how to publish an extension to Open VSX can be obtained [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by asbjornu** [comment]
As soon as we have auto-publishing to the VS Marketplace in order, we'd love a PR that adds auto-publish to any other marketplace.

**Comment by madmath03** [comment]
This would also be great for integration with [Gitpod](https://gitpod.io/)

**Comment by asbjornu** [comment]
Now that #40 is merged and version 1.3.0 is out the door, we happily accept pull requests integrating this into the `publish.yml` GitHub Actions workflow.

**Comment by madmath03** [comment]
Based on this [documentation](https://github.com/HaaLeo/publish-vscode-extension#readme), it seems that this call to npm vsce:
https://github.com/remarkjs/vscode-remark/blob/abd4a0e5cb793f61079004f4059149c7ec16e2a4/.github/workflows/publish.yml#L39-L40

could be replaced by this GitHub Action:
```yml
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v0
        id: publishToOpenVSX
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.VSCE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
          packagePath: ''
```
