### ISSUE TITLE
Add support for previewing markdown

### ISSUE THREAD

**Issue by wooorm** [remarkjs/vscode-remark#86]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

The VSCode markdown previewer uses markdown-it, which does not support GFM, and does not support (of course) the used remark plugins.

### Solution

Something like https://github.com/shd101wyy/mume probably, around unified.

It’s only really useful when the output is HTML, so for remark, we should probably find a `.remarkrc` and inject `remark-rehype`, `rehype-etc` afterwards?

Is it one underlying project that supports Atom, VS Code, and other editors, and supports either remark or rehype? Or should there be separate projects for remark and rehype too? Or?

What about MDX?
CSS?

### Alternatives

n/a

---

/cc @voxpelli

**Comment by wooorm** [comment]
Linking https://twitter.com/remcohaszing/status/1481699749409480704 /cc @remcohaszing

**Comment by remcohaszing** [comment]
I imagine this to be based on https://github.com/unifiedjs/unified-engine/issues/56.

The same override functionality can be used, but instead of using a `files` override, a context override can be defined. The language server could then handle a command to process a file based on a context, i.e. a hardcoded `preview` context or a configurable setting, or maybe a command parameter? I’m not entirely sure what options we have here.

```yaml
plugins:
  # Linting and auto formatting
  - remark-gfm
  - remark-preset-lint-recommended

overrides:
  # Override for linting MDX files as specified in https://github.com/unifiedjs/unified-engine/issues/56
  - files: ['*.mdx']
    plugins:
      - remark-mdx

  # Override for rendering a preview
  - context: preview
    plugins:
      # custom remark plugins can be used
      - remark-toc
      # This will probably always be required
      - remark-rehype
      # rehype plugins can be used as well!
      - rehype-autolink-headings
```
